"""Unit tests for the lifecycle hook driver (no OpenSearch required).

These patch ``save_memory_impl`` so they exercise payload parsing / dispatch
without touching a cluster. They intentionally do NOT carry the
``OPENSEARCH_URL`` skip guard used by the integration tests.
"""

import io
import json
import sys

import pytest


def _run(monkeypatch, payload, argv, env=None):
    """Drive hook.main() with a fake stdin/argv/env; return recorded save calls."""
    import opensearch_memory_mcp.hook as hook
    import opensearch_memory_mcp.server as server_mod

    calls = []

    def recorder(**kwargs):
        calls.append(kwargs)
        return json.dumps({"status": "saved", "id": "x", "session_id": kwargs.get("session_id", "")})

    monkeypatch.setattr(server_mod, "save_memory_impl", recorder)
    monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(payload)))
    monkeypatch.setattr(sys, "argv", argv)

    # KIRO_SESSION_ID must be controlled per-test (Kiro reads it from the env).
    monkeypatch.delenv("KIRO_SESSION_ID", raising=False)
    for k, v in (env or {}).items():
        monkeypatch.setenv(k, v)

    with pytest.raises(SystemExit) as exc:
        hook.main()
    assert exc.value.code == 0  # hooks must never block the agent
    return calls


KIRO_ARGV = ["prog", "hook", "--agent", "kiro"]


def test_kiro_user_prompt(monkeypatch):
    calls = _run(
        monkeypatch,
        {"hook_event_name": "userPromptSubmit", "cwd": "/home/u/myproj", "prompt": "fix the bug"},
        KIRO_ARGV,
        env={"KIRO_SESSION_ID": "sess-123"},
    )
    assert len(calls) == 1
    c = calls[0]
    assert c["role"] == "user"
    assert c["content"] == "fix the bug"
    assert c["agent_type"] == "kiro"
    assert c["session_id"] == "sess-123"  # pulled from KIRO_SESSION_ID env
    assert c["project"] == "myproj"       # basename of cwd


def test_kiro_stop_uses_inline_assistant_response(monkeypatch):
    calls = _run(
        monkeypatch,
        {"hook_event_name": "stop", "cwd": "/x", "assistant_response": "Done — all tests pass."},
        KIRO_ARGV,
        env={"KIRO_SESSION_ID": "sess-9"},
    )
    assert len(calls) == 1
    assert calls[0]["role"] == "assistant"
    assert calls[0]["content"] == "Done — all tests pass."
    assert calls[0]["session_id"] == "sess-9"


def test_kiro_post_tool_use_records_tool_call(monkeypatch):
    calls = _run(
        monkeypatch,
        {
            "hook_event_name": "postToolUse",
            "cwd": "/x",
            "tool_name": "fs_read",
            "tool_input": {"path": "/etc/hosts"},
            "tool_response": {"success": True},
        },
        KIRO_ARGV,
        env={"KIRO_SESSION_ID": "sess-1"},
    )
    assert len(calls) == 1
    c = calls[0]
    assert c["role"] == "assistant"
    assert c["tool_calls"][0]["name"] == "fs_read"
    assert "hosts" in c["tool_calls"][0]["input"]


def test_kiro_skips_self_write(monkeypatch):
    # Logging our own save_memory MCP write would recurse — it must be skipped.
    calls = _run(
        monkeypatch,
        {
            "hook_event_name": "postToolUse",
            "cwd": "/x",
            "tool_name": "@opensearch-memory/save_memory",
            "tool_input": {},
            "tool_response": {},
        },
        KIRO_ARGV,
        env={"KIRO_SESSION_ID": "sess-1"},
    )
    assert calls == []


def test_kiro_blank_prompt_not_saved(monkeypatch):
    calls = _run(
        monkeypatch,
        {"hook_event_name": "userPromptSubmit", "cwd": "/x", "prompt": "   "},
        KIRO_ARGV,
        env={"KIRO_SESSION_ID": "sess-1"},
    )
    assert calls == []


def test_kiro_session_id_absent_autogenerated_downstream(monkeypatch):
    # When KIRO_SESSION_ID is unset and the payload has none, the hook passes an
    # empty session_id; save_memory_impl is responsible for generating one.
    calls = _run(
        monkeypatch,
        {"hook_event_name": "stop", "cwd": "/x", "assistant_response": "hi"},
        KIRO_ARGV,
        env={},
    )
    assert len(calls) == 1
    assert calls[0]["session_id"] == ""


def test_claude_backward_compat(monkeypatch):
    # No --agent flag => claude-code; PascalCase event; session id from payload.
    calls = _run(
        monkeypatch,
        {
            "hook_event_name": "UserPromptSubmit",
            "cwd": "/srv/app",
            "prompt": "hello",
            "session_id": "claude-sess",
        },
        ["prog", "hook"],
    )
    assert len(calls) == 1
    assert calls[0]["agent_type"] == "claude-code"
    assert calls[0]["session_id"] == "claude-sess"
    assert calls[0]["role"] == "user"


def test_invalid_json_exits_clean(monkeypatch):
    import opensearch_memory_mcp.hook as hook

    monkeypatch.setattr(sys, "stdin", io.StringIO("not json"))
    monkeypatch.setattr(sys, "argv", KIRO_ARGV)
    with pytest.raises(SystemExit) as exc:
        hook.main()
    assert exc.value.code == 0
